import { describe, it, expect } from "vitest";
import fixtures from "../src/lib/tools/finance-fixtures.generated.json";
import {
  computeEmi, computeApr, goldEligibleValuePaise, ltvPct, maxLendablePaise,
  smaForDpd, statusForDpd, bucketForDpd, daysPastDue, dateAtDpd,
} from "../src/lib/tools/finance";

const R = (rupees: number) => BigInt(Math.round(rupees * 100));

/**
 * The calculators publish the product's own arithmetic, so they have to BE the product's own
 * arithmetic.
 *
 * A marketing page that computes an annual percentage rate one way while the software generates a
 * Key Facts Statement another way is not a rounding difference — it is a false statement about a
 * document a borrower is entitled to rely on. The fixture is emitted by the product from its own
 * code (`scripts/emit-finance-fixtures.mjs`); these assert this repository reproduces every row.
 *
 * If one fails, do NOT adjust the expectation. Find out which side changed.
 */
describe("the calculators agree with the product, case for case", () => {
  it("has a fixture that was actually generated", () => {
    expect(fixtures.note).toMatch(/GENERATED by scripts\/emit-finance-fixtures\.mjs/);
    expect(fixtures.emi.length + fixtures.apr.length + fixtures.gold.length + fixtures.dpd.length)
      .toBeGreaterThan(20);
  });

  it("EMI", () => {
    for (const c of fixtures.emi) {
      expect(
        computeEmi(R(c.principalRupees), c.annualRatePct, c.months).toString(),
        `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m`,
      ).toBe(c.emiPaise);
    }
  });

  it("APR — the figure the Key Facts Statement discloses", () => {
    for (const c of fixtures.apr) {
      const emi = computeEmi(R(c.principalRupees), c.annualRatePct, c.months);
      expect(emi.toString()).toBe(c.emiPaise);
      expect(
        computeApr(R(c.principalRupees), R(c.upfrontChargesRupees), emi, c.months),
        `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m with ₹${c.upfrontChargesRupees} upfront`,
      ).toBe(c.aprPct);
    }
  });

  it("gold — mixed purity, eligible value, LTV and the cap", () => {
    for (const c of fixtures.gold) {
      const items = c.items.map((i) => ({ karat: i.karat, netGrams: i.netGrams }));
      const eligible = goldEligibleValuePaise(items, R(c.rate22kRupeesPerGram));
      expect(eligible.toString(), JSON.stringify(c.items)).toBe(c.eligiblePaise);
      expect(ltvPct(R(c.outstandingRupees), eligible)).toBe(c.ltvPct);
      expect(maxLendablePaise(eligible, c.capPct).toString()).toBe(c.maxLendablePaise);
    }
  });

  it("classification — status, SMA bucket and DPD band", () => {
    for (const c of fixtures.dpd) {
      expect(statusForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.status);
      expect(smaForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.sma);
      expect(bucketForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.bucket);
    }
  });
});

describe("the day-90 boundary, which is the one that moves a quarter", () => {
  it("day 90 is still SMA-2, day 91 is non-performing", () => {
    expect(statusForDpd(90)).toBe("OVERDUE");
    expect(smaForDpd(90)).toBe("SMA_2");
    expect(statusForDpd(91)).toBe("NPA");
  });

  it("counts whole days from the due date, with no time and no zone", () => {
    const due = new Date(Date.UTC(2026, 3, 5));
    expect(daysPastDue(due, new Date(Date.UTC(2026, 3, 5)))).toBe(0);
    expect(daysPastDue(due, new Date(Date.UTC(2026, 6, 4)))).toBe(90);
    expect(daysPastDue(due, new Date(Date.UTC(2026, 6, 5)))).toBe(91);
  });

  it("and reports the date each boundary falls on", () => {
    const due = new Date(Date.UTC(2026, 3, 5));
    expect(dateAtDpd(due, 91).toISOString().slice(0, 10)).toBe("2026-07-05");
  });
});
