import { describe, it, expect } from "vitest";
import fixtures from "../src/lib/tools/finance-fixtures.generated.json";
import {
  computeEmi, computeApr, goldEligibleValuePaise, ltvPct, maxLendablePaise,
  smaForDpd, statusForDpd, bucketForDpd, daysPastDue, dateAtDpd, amortise, flatRate,
} from "../src/lib/tools/finance";
import {
  RETURNS, applicable, quarterEnds, monthEnds, addDays, type Profile,
} from "../src/lib/tools/returns";
import { findLayer, type SbrAnswers } from "../src/lib/tools/sbr";

const R = (rupees: number) => BigInt(Math.round(rupees * 100));

/**
 * The calculators publish the product's own arithmetic, so they have to BE the product's own
 * arithmetic.
 *
 * A marketing page that computes an annual percentage rate one way while the software generates a
 * Key Facts Statement another way is not a rounding difference — it is a false statement about a
 * document a borrower is entitled to rely on. The fixture is emitted by the product from its own
 * code (`scripts/emit-finance-fixtures.mjs`); these assert this repository reproduces every row.
 *
 * If one fails, do NOT adjust the expectation. Find out which side changed.
 */
describe("the calculators agree with the product, case for case", () => {
  it("has a fixture that was actually generated", () => {
    expect(fixtures.note).toMatch(/GENERATED by scripts\/emit-finance-fixtures\.mjs/);
    expect(fixtures.emi.length + fixtures.apr.length + fixtures.gold.length + fixtures.dpd.length)
      .toBeGreaterThan(20);
  });

  it("EMI", () => {
    for (const c of fixtures.emi) {
      expect(
        computeEmi(R(c.principalRupees), c.annualRatePct, c.months).toString(),
        `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m`,
      ).toBe(c.emiPaise);
    }
  });

  it("APR — the figure the Key Facts Statement discloses", () => {
    for (const c of fixtures.apr) {
      const emi = computeEmi(R(c.principalRupees), c.annualRatePct, c.months);
      expect(emi.toString()).toBe(c.emiPaise);
      expect(
        computeApr(R(c.principalRupees), R(c.upfrontChargesRupees), emi, c.months),
        `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m with ₹${c.upfrontChargesRupees} upfront`,
      ).toBe(c.aprPct);
    }
  });

  it("gold — mixed purity, eligible value, LTV and the cap", () => {
    for (const c of fixtures.gold) {
      const items = c.items.map((i) => ({ karat: i.karat, netGrams: i.netGrams }));
      const eligible = goldEligibleValuePaise(items, R(c.rate22kRupeesPerGram));
      expect(eligible.toString(), JSON.stringify(c.items)).toBe(c.eligiblePaise);
      expect(ltvPct(R(c.outstandingRupees), eligible)).toBe(c.ltvPct);
      expect(maxLendablePaise(eligible, c.capPct).toString()).toBe(c.maxLendablePaise);
    }
  });

  it("classification — status, SMA bucket and DPD band", () => {
    for (const c of fixtures.dpd) {
      expect(statusForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.status);
      expect(smaForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.sma);
      expect(bucketForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.bucket);
    }
  });
});

describe("the day-90 boundary, which is the one that moves a quarter", () => {
  it("day 90 is still SMA-2, day 91 is non-performing", () => {
    expect(statusForDpd(90)).toBe("OVERDUE");
    expect(smaForDpd(90)).toBe("SMA_2");
    expect(statusForDpd(91)).toBe("NPA");
  });

  it("counts whole days from the due date, with no time and no zone", () => {
    const due = new Date(Date.UTC(2026, 3, 5));
    expect(daysPastDue(due, new Date(Date.UTC(2026, 3, 5)))).toBe(0);
    expect(daysPastDue(due, new Date(Date.UTC(2026, 6, 4)))).toBe(90);
    expect(daysPastDue(due, new Date(Date.UTC(2026, 6, 5)))).toBe(91);
  });

  it("and reports the date each boundary falls on", () => {
    const due = new Date(Date.UTC(2026, 3, 5));
    expect(dateAtDpd(due, 91).toISOString().slice(0, 10)).toBe("2026-07-05");
  });
});

/**
 * The returns calendar states a REGULATORY OBLIGATION, under a named Company Secretary's byline.
 *
 * A calculator that is wrong gives a wrong number. This being wrong tells an NBFC it does not have
 * to file something it does have to file — so the applicability rules are pinned case by case, and
 * each case names the fact that drives it.
 *
 * Source: Master Direction – Reserve Bank of India (Filing of Supervisory Returns) Directions, 2024
 * (27 February 2024), read with the Scale Based Regulation Directions, 2023. If a rule below changes
 * because the Direction changed, update the Direction reference on the page in the same commit.
 */
describe("which returns apply, by layer and category", () => {
  const base = (over: Partial<Profile> = {}): Profile => ({
    layer: "BASE", category: "ICC", assetsCrore: 250,
    acceptsDeposits: false, hasOverseasInvestment: false, ...over,
  });
  const codes = (p: Profile) => applicable(p).map((r) => r.code).sort();

  it("a small Base Layer lender files the combined return, not the split pair", () => {
    const c = codes(base({ assetsCrore: 50 }));
    expect(c).toContain("DNBS02");
    expect(c).not.toContain("DNBS01");
    expect(c).not.toContain("DNBS03");
  });

  it("under ₹100 crore it files no liquidity returns", () => {
    const c = codes(base({ assetsCrore: 50 }));
    expect(c).not.toContain("DNBS04A");
    expect(c).not.toContain("DNBS04B");
  });

  it("at ₹100 crore the liquidity returns start — and 04B is MONTHLY", () => {
    const c = codes(base({ assetsCrore: 100 }));
    expect(c).toContain("DNBS04A");
    expect(c).toContain("DNBS04B");
    expect(RETURNS.find((r) => r.code === "DNBS04B")!.frequency).toBe("MONTHLY");
  });

  it("CRILC starts at ₹500 crore for a Base Layer ICC, and not before", () => {
    expect(codes(base({ assetsCrore: 499 }))).not.toContain("DNBS08");
    expect(codes(base({ assetsCrore: 500 }))).toContain("DNBS08");
    // And the SMA leg is weekly, not quarterly.
    expect(RETURNS.find((r) => r.code === "DNBS09")!.frequency).toBe("WEEKLY");
  });

  it("a Base Layer category that is not ICC, MFI or Factor stays out of CRILC however large", () => {
    expect(codes(base({ category: "AA", assetsCrore: 5000 }))).not.toContain("DNBS08");
  });

  it("Middle and Upper Layer file the split pair and CRILC regardless of size", () => {
    for (const layer of ["MIDDLE", "UPPER"] as const) {
      const c = codes(base({ layer, assetsCrore: 10 }));
      expect(c, layer).toContain("DNBS01");
      expect(c, layer).toContain("DNBS03");
      expect(c, layer).toContain("DNBS08");
      expect(c, layer).not.toContain("DNBS02");
    }
  });

  it("a core investment company files its own pair and no CRILC", () => {
    const c = codes(base({ layer: "MIDDLE", category: "CIC" }));
    expect(c).toContain("DNBS11");
    expect(c).toContain("DNBS12");
    expect(c).not.toContain("DNBS01");
    expect(c).not.toContain("DNBS03");
    expect(c).not.toContain("DNBS08");
  });

  it("a peer-to-peer platform files DNBS14 instead of DNBS02", () => {
    const c = codes(base({ category: "P2P" }));
    expect(c).toContain("DNBS14");
    expect(c).not.toContain("DNBS02");
  });

  it("the overseas return appears only when there is an overseas holding", () => {
    expect(codes(base())).not.toContain("DNBS13");
    expect(codes(base({ hasOverseasInvestment: true }))).toContain("DNBS13");
  });

  it("the auditor certificate applies to everybody, in every layer", () => {
    for (const layer of ["BASE", "MIDDLE", "UPPER"] as const) {
      expect(codes(base({ layer })), layer).toContain("DNBS10");
    }
  });

  it("every return says why, whether it applies or not", () => {
    const p = base();
    for (const r of RETURNS) {
      expect(r.why(p).length, r.code).toBeGreaterThan(20);
    }
  });
});

describe("the dates the calendar computes", () => {
  it("quarters end on the Indian financial year, not the calendar one", () => {
    const q = quarterEnds(2026).map((d) => d.toISOString().slice(0, 10));
    expect(q).toEqual(["2026-06-30", "2026-09-30", "2026-12-31", "2027-03-31"]);
  });

  it("a 21-day return for Q1 falls due on 21 July", () => {
    expect(addDays(quarterEnds(2026)[0], 21).toISOString().slice(0, 10)).toBe("2026-07-21");
  });

  it("twelve month-ends, April through March", () => {
    const m = monthEnds(2026).map((d) => d.toISOString().slice(0, 10));
    expect(m).toHaveLength(12);
    expect(m[0]).toBe("2026-04-30");
    expect(m[11]).toBe("2027-03-31");
  });
});

describe("the schedule, and what a flat rate really costs", () => {
  it("every schedule closes at exactly zero, and the components sum to the loan", () => {
    for (const c of fixtures.schedule) {
      const rows = amortise(R(c.principalRupees), c.annualRatePct, c.months);
      const label = `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m`;
      expect(rows.length, label).toBe(c.rows);
      expect(rows[rows.length - 1].closingPaise.toString(), label).toBe("0");
      expect(
        rows.reduce((s, r) => s + r.principalPaise, 0n).toString(),
        `${label}: principal components must sum to the sanctioned amount`,
      ).toBe(R(c.principalRupees).toString());
      expect(rows[0].emiPaise.toString(), label).toBe(c.firstEmiPaise);
      expect(rows[rows.length - 1].emiPaise.toString(), label).toBe(c.lastEmiPaise);
      expect(rows.reduce((s, r) => s + r.interestPaise, 0n).toString(), label).toBe(c.interestSumPaise);
    }
  });

  it("a flat rate resolves to the reducing rate the product discloses", () => {
    for (const c of fixtures.flat) {
      const f = flatRate(R(c.principalRupees), c.flatRatePct, c.months);
      const label = `₹${c.principalRupees} at ${c.flatRatePct}% flat for ${c.months}m`;
      expect(f.emiPaise.toString(), label).toBe(c.emiPaise);
      expect(f.effectiveReducingPct, label).toBe(c.effectiveReducingPct);
    }
  });

  it("and it is far higher than the flat number — which is the point of disclosing it", () => {
    const f = flatRate(R(500000), 12, 24);
    expect(f.effectiveReducingPct).toBeGreaterThan(20);
  });
});

/**
 * The layer decides which prudential regime an NBFC is under, so each rule is pinned by the fact
 * that drives it — and the precedence between them matters as much as the rules themselves.
 *
 * Source: Master Direction – RBI (Non-Banking Financial Company – Scale Based Regulation)
 * Directions, 2023.
 */
describe("which layer an NBFC is in", () => {
  const ask = (over: Partial<SbrAnswers> = {}): SbrAnswers => ({
    category: "ICC", acceptsDeposits: false, assetsCrore: 250,
    noPublicFunds: false, noCustomerInterface: false, namedInUpperLayerList: false, ...over,
  });

  it("small, non-deposit-taking, ordinary category → Base", () => {
    expect(findLayer(ask()).layer).toBe("BASE");
  });

  it("the ₹1,000 crore threshold moves a non-deposit-taking NBFC up", () => {
    expect(findLayer(ask({ assetsCrore: 999 })).layer).toBe("BASE");
    expect(findLayer(ask({ assetsCrore: 1000 })).layer).toBe("MIDDLE");
  });

  it("taking deposits beats the size test, however small", () => {
    const r = findLayer(ask({ acceptsDeposits: true, assetsCrore: 5 }));
    expect(r.layer).toBe("MIDDLE");
    expect(r.because).toMatch(/whatever its asset size/);
  });

  it("P2P, AA and NOFHC stay in the Base Layer at any size", () => {
    for (const category of ["P2P", "AA", "NOFHC"] as const) {
      expect(findLayer(ask({ category, assetsCrore: 50000 })).layer, category).toBe("BASE");
    }
  });

  it("CIC, HFC, IFC, IDF and SPD are Middle Layer at any size", () => {
    for (const category of ["CIC", "HFC", "IFC", "IDF", "SPD"] as const) {
      expect(findLayer(ask({ category, assetsCrore: 1 })).layer, category).toBe("MIDDLE");
    }
  });

  it("being NAMED by the Bank beats every other rule", () => {
    const r = findLayer(ask({ namedInUpperLayerList: true, category: "P2P", assetsCrore: 1 }));
    expect(r.layer).toBe("UPPER");
    expect(r.because).toMatch(/designation, not a threshold/);
  });

  it("says WHY, every time, and the reason names the deciding fact", () => {
    for (const a of [ask(), ask({ acceptsDeposits: true }), ask({ category: "HFC" }), ask({ assetsCrore: 5000 })]) {
      expect(findLayer(a).because.length).toBeGreaterThan(30);
    }
  });

  it("does not apply the PROPOSED ₹1 lakh crore Upper Layer test", () => {
    // Proposed April 2026 and not in force. A tool that acts on a consultation paper is guessing.
    expect(findLayer(ask({ assetsCrore: 150000 })).layer).toBe("MIDDLE");
  });
});
