import { describe, it, expect } from "vitest";
import fixtures from "../src/lib/tools/finance-fixtures.generated.json";
import {
  computeEmi, computeApr, goldEligibleValuePaise, ltvPct, maxLendablePaise,
  smaForDpd, statusForDpd, bucketForDpd, daysPastDue, dateAtDpd, amortise, flatRate, capForAdvance, maxAdvanceBanded,
} from "../src/lib/tools/finance";
import {
  RETURNS, applicable, quarterEnds, monthEnds, addDays, type Profile,
} from "../src/lib/tools/returns";
import { findLayer, type SbrAnswers } from "../src/lib/tools/sbr";
import { penalCharge, type PenalInput } from "../src/lib/tools/penal";
import { KFS_FIELDS, KFS_RULES, kfsGaps } from "../src/lib/tools/kfs";
import { provisionFor, DOUBTFUL_SECURED, BANK_DOUBTFUL_SECURED } from "../src/lib/tools/provision";
import { prepaymentEligibility, MSE_CAP_PAISE } from "../src/lib/tools/prepayment";

const R = (rupees: number) => BigInt(Math.round(rupees * 100));

/**
 * The calculators publish the product's own arithmetic, so they have to BE the product's own
 * arithmetic.
 *
 * A marketing page that computes an annual percentage rate one way while the software generates a
 * Key Facts Statement another way is not a rounding difference — it is a false statement about a
 * document a borrower is entitled to rely on. The fixture is emitted by the product from its own
 * code (`scripts/emit-finance-fixtures.mjs`); these assert this repository reproduces every row.
 *
 * If one fails, do NOT adjust the expectation. Find out which side changed.
 */
describe("the calculators agree with the product, case for case", () => {
  it("has a fixture that was actually generated", () => {
    expect(fixtures.note).toMatch(/GENERATED by scripts\/emit-finance-fixtures\.mjs/);
    expect(fixtures.emi.length + fixtures.apr.length + fixtures.gold.length + fixtures.dpd.length)
      .toBeGreaterThan(20);
  });

  it("EMI", () => {
    for (const c of fixtures.emi) {
      expect(
        computeEmi(R(c.principalRupees), c.annualRatePct, c.months).toString(),
        `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m`,
      ).toBe(c.emiPaise);
    }
  });

  it("APR — the figure the Key Facts Statement discloses", () => {
    for (const c of fixtures.apr) {
      const emi = computeEmi(R(c.principalRupees), c.annualRatePct, c.months);
      expect(emi.toString()).toBe(c.emiPaise);
      expect(
        computeApr(R(c.principalRupees), R(c.upfrontChargesRupees), emi, c.months),
        `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m with ₹${c.upfrontChargesRupees} upfront`,
      ).toBe(c.aprPct);
    }
  });

  it("gold — mixed purity, eligible value, LTV and the cap", () => {
    for (const c of fixtures.gold) {
      const items = c.items.map((i) => ({ karat: i.karat, netGrams: i.netGrams }));
      const eligible = goldEligibleValuePaise(items, R(c.rate22kRupeesPerGram));
      expect(eligible.toString(), JSON.stringify(c.items)).toBe(c.eligiblePaise);
      expect(ltvPct(R(c.outstandingRupees), eligible)).toBe(c.ltvPct);
      expect(maxLendablePaise(eligible, c.capPct).toString()).toBe(c.maxLendablePaise);
    }
  });

  it("classification — status, SMA bucket and DPD band", () => {
    for (const c of fixtures.dpd) {
      expect(statusForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.status);
      expect(smaForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.sma);
      expect(bucketForDpd(c.dpd), `dpd ${c.dpd}`).toBe(c.bucket);
    }
  });
});

describe("the day-90 boundary, which is the one that moves a quarter", () => {
  it("day 90 is still SMA-2, day 91 is non-performing", () => {
    expect(statusForDpd(90)).toBe("OVERDUE");
    expect(smaForDpd(90)).toBe("SMA_2");
    expect(statusForDpd(91)).toBe("NPA");
  });

  it("counts whole days from the due date, with no time and no zone", () => {
    const due = new Date(Date.UTC(2026, 3, 5));
    expect(daysPastDue(due, new Date(Date.UTC(2026, 3, 5)))).toBe(0);
    expect(daysPastDue(due, new Date(Date.UTC(2026, 6, 4)))).toBe(90);
    expect(daysPastDue(due, new Date(Date.UTC(2026, 6, 5)))).toBe(91);
  });

  it("and reports the date each boundary falls on", () => {
    const due = new Date(Date.UTC(2026, 3, 5));
    expect(dateAtDpd(due, 91).toISOString().slice(0, 10)).toBe("2026-07-05");
  });
});

/**
 * The returns calendar states a REGULATORY OBLIGATION, under a named Company Secretary's byline.
 *
 * A calculator that is wrong gives a wrong number. This being wrong tells an NBFC it does not have
 * to file something it does have to file — so the applicability rules are pinned case by case, and
 * each case names the fact that drives it.
 *
 * Source: Master Direction – Reserve Bank of India (Filing of Supervisory Returns) Directions, 2024
 * (27 February 2024), read with the Scale Based Regulation Directions, 2023. If a rule below changes
 * because the Direction changed, update the Direction reference on the page in the same commit.
 */
describe("which returns apply, by layer and category", () => {
  const base = (over: Partial<Profile> = {}): Profile => ({
    layer: "BASE", category: "ICC", assetsCrore: 250,
    acceptsDeposits: false, hasOverseasInvestment: false, ...over,
  });
  const codes = (p: Profile) => applicable(p).map((r) => r.code).sort();

  it("a small Base Layer lender files the combined return, not the split pair", () => {
    const c = codes(base({ assetsCrore: 50 }));
    expect(c).toContain("DNBS02");
    expect(c).not.toContain("DNBS01");
    expect(c).not.toContain("DNBS03");
  });

  it("under ₹100 crore it files no liquidity returns", () => {
    const c = codes(base({ assetsCrore: 50 }));
    expect(c).not.toContain("DNBS04A");
    expect(c).not.toContain("DNBS04B");
  });

  it("at ₹100 crore the liquidity returns start — and 04B is MONTHLY", () => {
    const c = codes(base({ assetsCrore: 100 }));
    expect(c).toContain("DNBS04A");
    expect(c).toContain("DNBS04B");
    expect(RETURNS.find((r) => r.code === "DNBS04B")!.frequency).toBe("MONTHLY");
  });

  it("CRILC starts at ₹500 crore for a Base Layer ICC, and not before", () => {
    expect(codes(base({ assetsCrore: 499 }))).not.toContain("DNBS08");
    expect(codes(base({ assetsCrore: 500 }))).toContain("DNBS08");
    // And the SMA leg is weekly, not quarterly.
    expect(RETURNS.find((r) => r.code === "DNBS09")!.frequency).toBe("WEEKLY");
  });

  it("a Base Layer category that is not ICC, MFI or Factor stays out of CRILC however large", () => {
    expect(codes(base({ category: "AA", assetsCrore: 5000 }))).not.toContain("DNBS08");
  });

  it("Middle and Upper Layer file the split pair and CRILC regardless of size", () => {
    for (const layer of ["MIDDLE", "UPPER"] as const) {
      const c = codes(base({ layer, assetsCrore: 10 }));
      expect(c, layer).toContain("DNBS01");
      expect(c, layer).toContain("DNBS03");
      expect(c, layer).toContain("DNBS08");
      expect(c, layer).not.toContain("DNBS02");
    }
  });

  it("a core investment company files its own pair and no CRILC", () => {
    const c = codes(base({ layer: "MIDDLE", category: "CIC" }));
    expect(c).toContain("DNBS11");
    expect(c).toContain("DNBS12");
    expect(c).not.toContain("DNBS01");
    expect(c).not.toContain("DNBS03");
    expect(c).not.toContain("DNBS08");
  });

  it("a peer-to-peer platform files DNBS14 instead of DNBS02", () => {
    const c = codes(base({ category: "P2P" }));
    expect(c).toContain("DNBS14");
    expect(c).not.toContain("DNBS02");
  });

  it("the overseas return appears only when there is an overseas holding", () => {
    expect(codes(base())).not.toContain("DNBS13");
    expect(codes(base({ hasOverseasInvestment: true }))).toContain("DNBS13");
  });

  it("the auditor certificate applies to everybody, in every layer", () => {
    for (const layer of ["BASE", "MIDDLE", "UPPER"] as const) {
      expect(codes(base({ layer })), layer).toContain("DNBS10");
    }
  });

  it("every return says why, whether it applies or not", () => {
    const p = base();
    for (const r of RETURNS) {
      expect(r.why(p).length, r.code).toBeGreaterThan(20);
    }
  });
});

describe("the dates the calendar computes", () => {
  it("quarters end on the Indian financial year, not the calendar one", () => {
    const q = quarterEnds(2026).map((d) => d.toISOString().slice(0, 10));
    expect(q).toEqual(["2026-06-30", "2026-09-30", "2026-12-31", "2027-03-31"]);
  });

  it("a 21-day return for Q1 falls due on 21 July", () => {
    expect(addDays(quarterEnds(2026)[0], 21).toISOString().slice(0, 10)).toBe("2026-07-21");
  });

  it("twelve month-ends, April through March", () => {
    const m = monthEnds(2026).map((d) => d.toISOString().slice(0, 10));
    expect(m).toHaveLength(12);
    expect(m[0]).toBe("2026-04-30");
    expect(m[11]).toBe("2027-03-31");
  });
});

describe("the schedule, and what a flat rate really costs", () => {
  it("every schedule closes at exactly zero, and the components sum to the loan", () => {
    for (const c of fixtures.schedule) {
      const rows = amortise(R(c.principalRupees), c.annualRatePct, c.months);
      const label = `₹${c.principalRupees} at ${c.annualRatePct}% for ${c.months}m`;
      expect(rows.length, label).toBe(c.rows);
      expect(rows[rows.length - 1].closingPaise.toString(), label).toBe("0");
      expect(
        rows.reduce((s, r) => s + r.principalPaise, 0n).toString(),
        `${label}: principal components must sum to the sanctioned amount`,
      ).toBe(R(c.principalRupees).toString());
      expect(rows[0].emiPaise.toString(), label).toBe(c.firstEmiPaise);
      expect(rows[rows.length - 1].emiPaise.toString(), label).toBe(c.lastEmiPaise);
      expect(rows.reduce((s, r) => s + r.interestPaise, 0n).toString(), label).toBe(c.interestSumPaise);
    }
  });

  it("a flat rate resolves to the reducing rate the product discloses", () => {
    for (const c of fixtures.flat) {
      const f = flatRate(R(c.principalRupees), c.flatRatePct, c.months);
      const label = `₹${c.principalRupees} at ${c.flatRatePct}% flat for ${c.months}m`;
      expect(f.emiPaise.toString(), label).toBe(c.emiPaise);
      expect(f.effectiveReducingPct, label).toBe(c.effectiveReducingPct);
    }
  });

  it("and it is far higher than the flat number — which is the point of disclosing it", () => {
    const f = flatRate(R(500000), 12, 24);
    expect(f.effectiveReducingPct).toBeGreaterThan(20);
  });
});

/**
 * The layer decides which prudential regime an NBFC is under, so each rule is pinned by the fact
 * that drives it — and the precedence between them matters as much as the rules themselves.
 *
 * Source: Master Direction – RBI (Non-Banking Financial Company – Scale Based Regulation)
 * Directions, 2023.
 */
describe("which layer an NBFC is in", () => {
  const ask = (over: Partial<SbrAnswers> = {}): SbrAnswers => ({
    category: "ICC", acceptsDeposits: false, assetsCrore: 250,
    noPublicFunds: false, noCustomerInterface: false, namedInUpperLayerList: false, ...over,
  });

  it("small, non-deposit-taking, ordinary category → Base", () => {
    expect(findLayer(ask()).layer).toBe("BASE");
  });

  it("the ₹1,000 crore threshold moves a non-deposit-taking NBFC up", () => {
    expect(findLayer(ask({ assetsCrore: 999 })).layer).toBe("BASE");
    expect(findLayer(ask({ assetsCrore: 1000 })).layer).toBe("MIDDLE");
  });

  it("taking deposits beats the size test, however small", () => {
    const r = findLayer(ask({ acceptsDeposits: true, assetsCrore: 5 }));
    expect(r.layer).toBe("MIDDLE");
    expect(r.because).toMatch(/whatever its asset size/);
  });

  it("P2P, AA and NOFHC stay in the Base Layer at any size", () => {
    for (const category of ["P2P", "AA", "NOFHC"] as const) {
      expect(findLayer(ask({ category, assetsCrore: 50000 })).layer, category).toBe("BASE");
    }
  });

  it("CIC, HFC, IFC, IDF and SPD are Middle Layer at any size", () => {
    for (const category of ["CIC", "HFC", "IFC", "IDF", "SPD"] as const) {
      expect(findLayer(ask({ category, assetsCrore: 1 })).layer, category).toBe("MIDDLE");
    }
  });

  it("being NAMED by the Bank beats every other rule", () => {
    const r = findLayer(ask({ namedInUpperLayerList: true, category: "P2P", assetsCrore: 1 }));
    expect(r.layer).toBe("UPPER");
    expect(r.because).toMatch(/designation, not a threshold/);
  });

  it("says WHY, every time, and the reason names the deciding fact", () => {
    for (const a of [ask(), ask({ acceptsDeposits: true }), ask({ category: "HFC" }), ask({ assetsCrore: 5000 })]) {
      expect(findLayer(a).because.length).toBeGreaterThan(30);
    }
  });

  it("does not apply the PROPOSED ₹1 lakh crore Upper Layer test", () => {
    // Proposed April 2026 and not in force. A tool that acts on a consultation paper is guessing.
    expect(findLayer(ask({ assetsCrore: 150000 })).layer).toBe("MIDDLE");
  });
});

/**
 * The gold cap is three bands, not one number — and the tool defaulted to the strictest.
 *
 * Effective 1 April 2026: 85% up to ₹2.5 lakh, 80% to ₹5 lakh, 75% above. Most gold loans written
 * in India are small, so a flat 75% understates what may be advanced on the majority of them.
 *
 * Source: RBI (Lending Against Gold and Silver Collateral) Directions, 2025.
 */
describe("the gold LTV cap depends on the size of the advance", () => {
  const L = (rupees: number) => BigInt(Math.round(rupees * 100));

  it("picks the band from the advance", () => {
    expect(capForAdvance(L(100000)).capPct).toBe(85);
    expect(capForAdvance(L(250000)).capPct).toBe(85);
    expect(capForAdvance(L(250001)).capPct).toBe(80);
    expect(capForAdvance(L(500000)).capPct).toBe(80);
    expect(capForAdvance(L(500001)).capPct).toBe(75);
  });

  it("a small packet gets the 85% band, not 75%", () => {
    // 40g of 22K at ₹6,800 = ₹2,72,000 eligible.
    const r = maxAdvanceBanded(L(272000));
    expect(r.capPct).toBe(85);
    expect(r.advancePaise).toBe(L(231200));
    // The flat-75% answer this used to give.
    expect(r.advancePaise).toBeGreaterThan(L(204000));
  });

  it("a mid-sized packet lands in the 80% band", () => {
    const r = maxAdvanceBanded(L(600000));
    expect(r.capPct).toBe(80);
    expect(r.advancePaise).toBe(L(480000));
  });

  it("a large packet is capped at 75%", () => {
    const r = maxAdvanceBanded(L(1000000));
    expect(r.capPct).toBe(75);
    expect(r.advancePaise).toBe(L(750000));
  });

  it("never proposes an advance that would fall outside its own band", () => {
    for (const eligible of [50000, 250000, 294118, 300000, 625000, 666667, 700000, 2000000]) {
      const r = maxAdvanceBanded(L(eligible));
      expect(capForAdvance(r.advancePaise).capPct, `eligible ₹${eligible}`).toBe(r.capPct);
    }
  });
});

/**
 * Penal charges, on the rules the August 2023 circular actually set.
 *
 * Sources: RBI/2023-24/53 of 18 August 2023, effective 1 April 2024; 55th GST Council on
 * taxability. The arithmetic is simple; what the tool exists for is the four rules around it.
 */
describe("penal charges", () => {
  const base = (over: Partial<PenalInput> = {}): PenalInput => ({
    overdueRupees: 25000, daysOverdue: 45, basis: "PCT_PER_MONTH", rate: 2,
    graceDays: 0, consumerLoan: false, comparableNonIndividualRate: 2, ...over,
  });

  it("charges on the overdue amount for the days it was overdue", () => {
    // 25,000 x 2% x 45/30 = 750
    expect(penalCharge(base()).chargeRupees).toBe(750);
  });

  it("grace removes days from the charge, not from the count of days overdue", () => {
    const r = penalCharge(base({ graceDays: 15 }));
    expect(r.chargeableDays).toBe(30);
    expect(r.chargeRupees).toBe(500);
  });

  it("grace can take the charge to nil without the account ceasing to be overdue", () => {
    const r = penalCharge(base({ daysOverdue: 5, graceDays: 7 }));
    expect(r.chargeableDays).toBe(0);
    expect(r.chargeRupees).toBe(0);
  });

  it("a flat per-instance charge does not scale with days", () => {
    expect(penalCharge(base({ basis: "FLAT_PER_INSTANCE", rate: 500 })).chargeRupees).toBe(500);
    expect(penalCharge(base({ basis: "FLAT_PER_INSTANCE", rate: 500, daysOverdue: 400 })).chargeRupees).toBe(500);
  });

  it("flags a consumer rate above what a business borrower pays for the same breach", () => {
    const bad = penalCharge(base({ consumerLoan: true, rate: 3, comparableNonIndividualRate: 2 }));
    const cap = bad.checks.find((c) => c.label.includes("business borrower"))!;
    expect(cap.ok).toBe(false);
    expect(cap.detail).toMatch(/may not be higher/);
  });

  it("and passes it when the two are equal", () => {
    const ok = penalCharge(base({ consumerLoan: true, rate: 2, comparableNonIndividualRate: 2 }));
    expect(ok.checks.find((c) => c.label.includes("business borrower"))!.ok).toBe(true);
  });

  it("that check is only raised for a consumer loan", () => {
    expect(penalCharge(base({ consumerLoan: false })).checks.some((c) => c.label.includes("business borrower"))).toBe(false);
  });

  it("always states no capitalisation, no GST, and receipt-basis income", () => {
    const labels = penalCharge(base()).checks.map((c) => c.label).join(" | ");
    expect(labels).toMatch(/Not capitalised/);
    expect(labels).toMatch(/No GST/);
    expect(labels).toMatch(/when received/);
  });
});

/**
 * The KFS checklist, against Annex A of the 15 April 2024 circular.
 *
 * The conditional fields are the point: a checker that marks a fixed-rate loan incomplete for
 * missing the floating-rate particulars is a checker nobody finishes.
 */
describe("the Key Facts Statement checklist", () => {
  const none = new Set<string>();
  const all = { floating: true, lsp: true, colending: true };
  const plain = { floating: false, lsp: false, colending: false };

  it("covers the annexures as well as the statement", () => {
    const ids = KFS_FIELDS.map((f) => f.id);
    expect(ids).toContain("apr-sheet");
    expect(ids).toContain("schedule");
    expect(KFS_FIELDS.filter((f) => f.group === "Annexed")).toHaveLength(2);
  });

  it("every field says why it is there", () => {
    for (const f of KFS_FIELDS) expect(f.detail.length, f.id).toBeGreaterThan(30);
  });

  it("conditional fields are only required when their condition holds", () => {
    const gapIds = (a: typeof all) => kfsGaps(none, a).map((f) => f.id);
    expect(gapIds(plain)).not.toContain("floating");
    expect(gapIds(plain)).not.toContain("lsp");
    expect(gapIds(plain)).not.toContain("colending");
    expect(gapIds(all)).toContain("floating");
    expect(gapIds(all)).toContain("lsp");
    expect(gapIds(all)).toContain("colending");
  });

  it("and each conditional field states its condition", () => {
    for (const id of ["floating", "lsp", "colending"]) {
      expect(KFS_FIELDS.find((f) => f.id === id)!.onlyIf, id).toBeTruthy();
    }
  });

  it("a fully ticked plain-vanilla statement has no gaps", () => {
    const ticked = new Set(KFS_FIELDS.filter((f) => !f.onlyIf).map((f) => f.id));
    expect(kfsGaps(ticked, plain)).toHaveLength(0);
  });

  it("carries the four rules that are not fields", () => {
    const joined = KFS_RULES.join(" ");
    expect(joined).toMatch(/cannot be levied without the borrower/);
    expect(joined).toMatch(/on behalf of a third party/);
    expect(joined).toMatch(/part of the loan agreement/);
    expect(joined).toMatch(/1 October 2024/);
  });
});

describe("provisioning, at each classification", () => {
  const base = {
    layer: "BASE" as const,
    standardKind: "GENERAL" as const,
    doubtfulAge: "UPTO_1Y" as const,
    outstandingPaise: 100_000_000, // ₹10,00,000
    securedPaise: 0,
  };

  it("provides on a standard asset — it is not provision-free", () => {
    const r = provisionFor({ ...base, classification: "STANDARD" });
    expect(r.totalPaise).toBe(250_000); // ₹2,500 = 0.25%
    expect(r.effectivePct).toBe(0.25);
  });

  it("charges the Middle Layer a higher standard rate than the Base Layer", () => {
    const bl = provisionFor({ ...base, classification: "STANDARD" });
    const ml = provisionFor({ ...base, layer: "MIDDLE", classification: "STANDARD" });
    expect(ml.effectivePct).toBe(0.4);
    expect(ml.totalPaise).toBeGreaterThan(bl.totalPaise);
  });

  it("takes ten per cent of the WHOLE outstanding on a sub-standard asset, security or not", () => {
    const unsecured = provisionFor({ ...base, classification: "SUB_STANDARD" });
    const secured = provisionFor({ ...base, classification: "SUB_STANDARD", securedPaise: 100_000_000 });
    expect(unsecured.totalPaise).toBe(10_000_000); // ₹1,00,000
    expect(secured.totalPaise).toBe(unsecured.totalPaise);
  });

  /**
   * The reason this file exists. Publishing the bank table under an NBFC heading is a live error on
   * other sites, and at the far band it doubles the provision.
   */
  it("uses the NBFC doubtful rates, which are not the bank rates", () => {
    expect(DOUBTFUL_SECURED).toEqual({ UPTO_1Y: 20, "1_TO_3Y": 30, OVER_3Y: 50 });
    expect(BANK_DOUBTFUL_SECURED).toEqual({ UPTO_1Y: 25, "1_TO_3Y": 40, OVER_3Y: 100 });
    for (const age of ["UPTO_1Y", "1_TO_3Y", "OVER_3Y"] as const) {
      expect(DOUBTFUL_SECURED[age]).toBeLessThan(BANK_DOUBTFUL_SECURED[age]);
    }
  });

  it("splits a doubtful asset, and provides the unsecured part in full", () => {
    // The worked example on the blog: ₹40,00,000 outstanding, ₹28,00,000 realisable.
    const r = provisionFor({
      ...base, classification: "DOUBTFUL",
      outstandingPaise: 400_000_000, securedPaise: 280_000_000,
    });
    expect(r.totalPaise).toBe(176_000_000); // ₹5,60,000 + ₹12,00,000
    expect(r.effectivePct).toBe(44);
  });

  it("raises the secured rate with time in the doubtful category", () => {
    const at = (doubtfulAge: "UPTO_1Y" | "1_TO_3Y" | "OVER_3Y") =>
      provisionFor({
        ...base, classification: "DOUBTFUL", doubtfulAge,
        outstandingPaise: 400_000_000, securedPaise: 280_000_000,
      }).totalPaise;
    expect(at("UPTO_1Y")).toBe(176_000_000);
    expect(at("1_TO_3Y")).toBe(204_000_000);
    expect(at("OVER_3Y")).toBe(260_000_000); // ₹26,00,000 — a bank would say ₹40,00,000
  });

  it("provides a loss asset in full, however much security is held", () => {
    const r = provisionFor({
      ...base, classification: "LOSS",
      outstandingPaise: 400_000_000, securedPaise: 380_000_000,
    });
    expect(r.totalPaise).toBe(400_000_000);
    expect(r.effectivePct).toBe(100);
  });

  it("never provides on more than the outstanding, even if security is overstated", () => {
    const r = provisionFor({
      ...base, classification: "DOUBTFUL",
      outstandingPaise: 100_000_000, securedPaise: 500_000_000,
    });
    expect(r.totalPaise).toBeLessThanOrEqual(100_000_000);
  });
});

describe("whether a pre-payment charge may be levied", () => {
  const loan = {
    lender: "NBFC_ML" as const,
    borrower: "INDIVIDUAL" as const,
    purpose: "NON_BUSINESS" as const,
    rateAtPrepayment: "FLOATING" as const,
    sanctionedPaise: 250_000_000, // ₹25 lakh
    sanctionedOn: "2026-04-01",
  };

  it("bars the charge on a floating-rate personal loan, at any lender and any amount", () => {
    for (const lender of ["NBFC_BL", "NBFC_ML", "NBFC_UL", "COMMERCIAL_BANK", "SFB"] as const) {
      const r = prepaymentEligibility({ ...loan, lender, sanctionedPaise: 10_000_000_000 });
      expect(r.barred).toBe(true);
    }
  });

  /** The test is the rate at pre-payment, not at sanction — the dual-rate trap. */
  it("does not bar it where the loan is on a fixed rate when the borrower pre-pays", () => {
    expect(prepaymentEligibility({ ...loan, rateAtPrepayment: "FIXED" }).barred).toBe(false);
  });

  it("leaves a loan sanctioned before the Directions took effect alone", () => {
    const r = prepaymentEligibility({ ...loan, sanctionedOn: "2025-12-31" });
    expect(r.barred).toBe(false);
    expect(r.because).toContain("1 January 2026");
  });

  /**
   * The part of these Directions that is hardest to hold in the head: on a business-purpose loan
   * the same loan to the same borrower comes out differently at three lenders in a row.
   */
  it("splits business-purpose loans by lender tier, not by loan", () => {
    const biz = { ...loan, purpose: "BUSINESS" as const, borrower: "MSE" as const };
    const big = { ...biz, sanctionedPaise: 800_000_000 }; // ₹80 lakh, above the ₹50 lakh line

    expect(prepaymentEligibility({ ...big, lender: "COMMERCIAL_BANK" }).barred).toBe(true);
    expect(prepaymentEligibility({ ...big, lender: "NBFC_UL" }).barred).toBe(true);
    expect(prepaymentEligibility({ ...big, lender: "NBFC_ML" }).barred).toBe(false);
    expect(prepaymentEligibility({ ...biz, lender: "NBFC_ML" }).barred).toBe(true); // ₹25 lakh
    expect(prepaymentEligibility({ ...biz, lender: "NBFC_BL" }).barred).toBe(false);
  });

  it("measures the cap on the sanctioned amount, so paying down does not bring a loan inside it", () => {
    const at = (sanctionedPaise: number) =>
      prepaymentEligibility({
        ...loan, purpose: "BUSINESS", borrower: "MSE", lender: "NBFC_ML", sanctionedPaise,
      }).barred;
    expect(at(MSE_CAP_PAISE)).toBe(true);
    expect(at(MSE_CAP_PAISE + 1)).toBe(false);
  });

  it("does not reach a borrower who is neither an individual nor a small enterprise", () => {
    const r = prepaymentEligibility({
      ...loan, borrower: "OTHER", purpose: "BUSINESS", lender: "COMMERCIAL_BANK",
    });
    expect(r.barred).toBe(false);
  });
});
