/**
 * The same arithmetic the product runs, reimplemented here because the site cannot import it.
 *
 * These are not "close enough" versions for a marketing page. A lender who runs the APR calculator
 * and then sees a different figure on a Key Facts Statement generated by the software has been told
 * something false about a compliance obligation — which is worse than a wrong number, because it is
 * a wrong number about a document the borrower is entitled to rely on.
 *
 * So every function here is pinned. `finance-fixtures.generated.json` is emitted by the PRODUCT from
 * its own code, and `tests/tools.test.ts` asserts this file reproduces every row of it exactly. A
 * divergence fails the build and names the case. Regenerate the fixture from the product repo:
 *
 *     node scripts/emit-finance-fixtures.mjs
 *
 * Money is in paise as a whole number throughout, for the reason set out in the reconciliation post:
 * the fractions have to go somewhere, and it should be one deliberate place rather than everywhere.
 */

/** Round to the nearest rupee, in paise. The KFS quotes an instalment to the rupee. */
export const roundToRupee = (paise: bigint): bigint => {
  const r = paise % 100n;
  return r === 0n ? paise : paise - r + (r >= 50n ? 100n : 0n);
};

/**
 * Reducing-balance instalment, quoted to the rupee.
 *
 * Rounded here rather than at display time, because the figure the borrower is quoted and the figure
 * the account collects have to be the same one.
 */
export function computeEmi(principalPaise: bigint, annualRatePct: number, months: number): bigint {
  const P = Number(principalPaise);
  const r = annualRatePct / 12 / 100;
  if (months <= 0) return principalPaise;
  if (r === 0) return roundToRupee(BigInt(Math.round(P / months)));
  const f = Math.pow(1 + r, months);
  return roundToRupee(BigInt(Math.round((P * r * f) / (f - 1))));
}

/**
 * The annual percentage rate a Key Facts Statement must disclose.
 *
 * Not the interest rate. It is solved for: the rate at which the instalments the borrower actually
 * pays, discounted back, equal the money they actually RECEIVED — which is the sanctioned amount
 * less anything deducted up front. There is no closed form, so it is found by bisection.
 */
export function computeApr(
  principalPaise: bigint, upfrontChargesPaise: bigint, emiPaise: bigint, months: number,
): number {
  const net = Number(principalPaise) - Number(upfrontChargesPaise);
  const emi = Number(emiPaise);
  if (net <= 0 || emi <= 0 || months <= 0) return 0;
  const f = (r: number) => {
    let s = 0;
    for (let t = 1; t <= months; t++) s += emi / Math.pow(1 + r, t);
    return s - net;
  };
  let lo = 0, hi = 2;
  if (f(0) <= 0) return 0;
  for (let i = 0; i < 100; i++) {
    const mid = (lo + hi) / 2;
    if (f(mid) > 0) lo = mid;
    else hi = mid;
  }
  const monthly = (lo + hi) / 2;
  return Math.round(monthly * 12 * 100 * 100) / 100;
}

// ── Gold ─────────────────────────────────────────────────────────────────────

export interface GoldItem { karat: number; netGrams: number }

/**
 * A mixed packet valued on ONE basis.
 *
 * Ornaments come in at different purities and the reference rate is quoted for 22 carat, so each
 * item is converted to its 22-carat equivalent weight before it is priced. This is the step a hand
 * calculation usually skips, and it is why a 24-carat coin is worth more per gram than the rate.
 */
export const equivalent22k = (i: GoldItem): number => (i.netGrams * i.karat) / 22;

export function goldEligibleValuePaise(items: GoldItem[], rate22kPaisePerGram: bigint): bigint {
  let total = 0n;
  for (const it of items) total += BigInt(Math.round(equivalent22k(it) * Number(rate22kPaisePerGram)));
  return total;
}

/** Loan to value, to two decimals. */
export function ltvPct(outstandingPaise: bigint, eligiblePaise: bigint): number {
  if (eligiblePaise <= 0n) return outstandingPaise > 0n ? 9999 : 0;
  return Math.round((Number(outstandingPaise) / Number(eligiblePaise)) * 10000) / 100;
}

/** The most that may be advanced at a cap, floored — never rounded up past the cap. */
export function maxLendablePaise(eligiblePaise: bigint, capPct: number): bigint {
  return BigInt(Math.floor(Number(eligiblePaise) * (capPct / 100)));
}

// ── Classification ───────────────────────────────────────────────────────────

export type Sma = "STANDARD" | "SMA_0" | "SMA_1" | "SMA_2" | "NPA";
export type LoanStatus = "ACTIVE" | "OVERDUE" | "NPA";

export function smaForDpd(dpd: number): Sma {
  if (dpd <= 0) return "STANDARD";
  if (dpd <= 30) return "SMA_0";
  if (dpd <= 60) return "SMA_1";
  if (dpd <= 90) return "SMA_2";
  return "NPA";
}

/**
 * Non-performing on day 91, not day 90.
 *
 * IRACP makes an asset non-performing where an amount remains overdue for a period of MORE THAN
 * ninety days, so day ninety is still SMA-2. Getting this one day wrong moves the provision, the
 * income reversal and the figure sent to the credit bureaus into the wrong quarter — every time.
 */
export function statusForDpd(dpd: number): LoanStatus {
  if (dpd > 90) return "NPA";
  if (dpd >= 1) return "OVERDUE";
  return "ACTIVE";
}

export function bucketForDpd(dpd: number): string {
  if (dpd <= 0) return "CURRENT";
  if (dpd <= 30) return "DPD_1_30";
  if (dpd <= 60) return "DPD_31_60";
  if (dpd <= 90) return "DPD_61_90";
  if (dpd <= 120) return "DPD_91_120";
  if (dpd <= 150) return "DPD_121_150";
  if (dpd <= 180) return "DPD_151_180";
  return "DPD_181_PLUS";
}

/** Whole days from a due date to a given day. Dates only — no time, no zone. */
export function daysPastDue(dueDate: Date, asOn: Date): number {
  const d = Date.UTC(dueDate.getUTCFullYear(), dueDate.getUTCMonth(), dueDate.getUTCDate());
  const a = Date.UTC(asOn.getUTCFullYear(), asOn.getUTCMonth(), asOn.getUTCDate());
  return Math.max(0, Math.round((a - d) / 86_400_000));
}

/** The date an account reaches a given days-past-due count, from its due date. */
export const dateAtDpd = (dueDate: Date, dpd: number): Date =>
  new Date(Date.UTC(dueDate.getUTCFullYear(), dueDate.getUTCMonth(), dueDate.getUTCDate() + dpd));
