/**
 * The same arithmetic the product runs, reimplemented here because the site cannot import it.
 *
 * These are not "close enough" versions for a marketing page. A lender who runs the APR calculator
 * and then sees a different figure on a Key Facts Statement generated by the software has been told
 * something false about a compliance obligation — which is worse than a wrong number, because it is
 * a wrong number about a document the borrower is entitled to rely on.
 *
 * So every function here is pinned. `finance-fixtures.generated.json` is emitted by the PRODUCT from
 * its own code, and `tests/tools.test.ts` asserts this file reproduces every row of it exactly. A
 * divergence fails the build and names the case. Regenerate the fixture from the product repo:
 *
 *     node scripts/emit-finance-fixtures.mjs
 *
 * Money is in paise as a whole number throughout, for the reason set out in the reconciliation post:
 * the fractions have to go somewhere, and it should be one deliberate place rather than everywhere.
 */

/** Round to the nearest rupee, in paise. The KFS quotes an instalment to the rupee. */
export const roundToRupee = (paise: bigint): bigint => {
  const r = paise % 100n;
  return r === 0n ? paise : paise - r + (r >= 50n ? 100n : 0n);
};

/**
 * Reducing-balance instalment, quoted to the rupee.
 *
 * Rounded here rather than at display time, because the figure the borrower is quoted and the figure
 * the account collects have to be the same one.
 */
export function computeEmi(principalPaise: bigint, annualRatePct: number, months: number): bigint {
  const P = Number(principalPaise);
  const r = annualRatePct / 12 / 100;
  if (months <= 0) return principalPaise;
  if (r === 0) return roundToRupee(BigInt(Math.round(P / months)));
  const f = Math.pow(1 + r, months);
  return roundToRupee(BigInt(Math.round((P * r * f) / (f - 1))));
}

/**
 * The annual percentage rate a Key Facts Statement must disclose.
 *
 * Not the interest rate. It is solved for: the rate at which the instalments the borrower actually
 * pays, discounted back, equal the money they actually RECEIVED — which is the sanctioned amount
 * less anything deducted up front. There is no closed form, so it is found by bisection.
 */
export function computeApr(
  principalPaise: bigint, upfrontChargesPaise: bigint, emiPaise: bigint, months: number,
): number {
  const net = Number(principalPaise) - Number(upfrontChargesPaise);
  const emi = Number(emiPaise);
  if (net <= 0 || emi <= 0 || months <= 0) return 0;
  const f = (r: number) => {
    let s = 0;
    for (let t = 1; t <= months; t++) s += emi / Math.pow(1 + r, t);
    return s - net;
  };
  let lo = 0, hi = 2;
  if (f(0) <= 0) return 0;
  for (let i = 0; i < 100; i++) {
    const mid = (lo + hi) / 2;
    if (f(mid) > 0) lo = mid;
    else hi = mid;
  }
  const monthly = (lo + hi) / 2;
  return Math.round(monthly * 12 * 100 * 100) / 100;
}

// ── Gold ─────────────────────────────────────────────────────────────────────

export interface GoldItem { karat: number; netGrams: number }

/**
 * A mixed packet valued on ONE basis.
 *
 * Ornaments come in at different purities and the reference rate is quoted for 22 carat, so each
 * item is converted to its 22-carat equivalent weight before it is priced. This is the step a hand
 * calculation usually skips, and it is why a 24-carat coin is worth more per gram than the rate.
 */
export const equivalent22k = (i: GoldItem): number => (i.netGrams * i.karat) / 22;

export function goldEligibleValuePaise(items: GoldItem[], rate22kPaisePerGram: bigint): bigint {
  let total = 0n;
  for (const it of items) total += BigInt(Math.round(equivalent22k(it) * Number(rate22kPaisePerGram)));
  return total;
}

/** Loan to value, to two decimals. */
export function ltvPct(outstandingPaise: bigint, eligiblePaise: bigint): number {
  if (eligiblePaise <= 0n) return outstandingPaise > 0n ? 9999 : 0;
  return Math.round((Number(outstandingPaise) / Number(eligiblePaise)) * 10000) / 100;
}

/** The most that may be advanced at a cap, floored — never rounded up past the cap. */
export function maxLendablePaise(eligiblePaise: bigint, capPct: number): bigint {
  return BigInt(Math.floor(Number(eligiblePaise) * (capPct / 100)));
}

// ── Classification ───────────────────────────────────────────────────────────

export type Sma = "STANDARD" | "SMA_0" | "SMA_1" | "SMA_2" | "NPA";
export type LoanStatus = "ACTIVE" | "OVERDUE" | "NPA";

export function smaForDpd(dpd: number): Sma {
  if (dpd <= 0) return "STANDARD";
  if (dpd <= 30) return "SMA_0";
  if (dpd <= 60) return "SMA_1";
  if (dpd <= 90) return "SMA_2";
  return "NPA";
}

/**
 * Non-performing on day 91, not day 90.
 *
 * IRACP makes an asset non-performing where an amount remains overdue for a period of MORE THAN
 * ninety days, so day ninety is still SMA-2. Getting this one day wrong moves the provision, the
 * income reversal and the figure sent to the credit bureaus into the wrong quarter — every time.
 */
export function statusForDpd(dpd: number): LoanStatus {
  if (dpd > 90) return "NPA";
  if (dpd >= 1) return "OVERDUE";
  return "ACTIVE";
}

export function bucketForDpd(dpd: number): string {
  if (dpd <= 0) return "CURRENT";
  if (dpd <= 30) return "DPD_1_30";
  if (dpd <= 60) return "DPD_31_60";
  if (dpd <= 90) return "DPD_61_90";
  if (dpd <= 120) return "DPD_91_120";
  if (dpd <= 150) return "DPD_121_150";
  if (dpd <= 180) return "DPD_151_180";
  return "DPD_181_PLUS";
}

/** Whole days from a due date to a given day. Dates only — no time, no zone. */
export function daysPastDue(dueDate: Date, asOn: Date): number {
  const d = Date.UTC(dueDate.getUTCFullYear(), dueDate.getUTCMonth(), dueDate.getUTCDate());
  const a = Date.UTC(asOn.getUTCFullYear(), asOn.getUTCMonth(), asOn.getUTCDate());
  return Math.max(0, Math.round((a - d) / 86_400_000));
}

/** The date an account reaches a given days-past-due count, from its due date. */
export const dateAtDpd = (dueDate: Date, dpd: number): Date =>
  new Date(Date.UTC(dueDate.getUTCFullYear(), dueDate.getUTCMonth(), dueDate.getUTCDate() + dpd));

// ── The schedule ─────────────────────────────────────────────────────────────

export interface ScheduleRow {
  n: number;
  openingPaise: bigint;
  emiPaise: bigint;
  principalPaise: bigint;
  interestPaise: bigint;
  closingPaise: bigint;
}

const roundPaise = (n: number): bigint => BigInt(Math.round(n));

/**
 * The repayment schedule, and the rule most calculators leave out.
 *
 * Interest is charged on the balance still outstanding, the instalment is level, and **the final
 * instalment absorbs every rounding difference** so the principal components sum to the sanctioned
 * amount exactly and the closing balance is zero — not "about zero".
 *
 * That last rule is the difference between a schedule a lender can put in a loan agreement and one
 * that is off by a few rupees against the amount the borrower actually signed for.
 */
export function amortise(principalPaise: bigint, annualRatePct: number, months: number): ScheduleRow[] {
  if (months <= 0 || principalPaise <= 0n) return [];
  const periodRate = annualRatePct / 12 / 100;
  const emi = computeEmi(principalPaise, annualRatePct, months);
  const rows: ScheduleRow[] = [];
  let opening = principalPaise;
  for (let i = 0; i < months; i++) {
    const interest = roundPaise(Number(opening) * periodRate);
    const last = i === months - 1;
    const principal = last ? opening : emi - interest;
    const emiAmount = last ? principal + interest : emi;
    const closing = opening - principal;
    rows.push({ n: i + 1, openingPaise: opening, emiPaise: emiAmount, principalPaise: principal, interestPaise: interest, closingPaise: closing });
    opening = closing;
  }
  return rows;
}

// ── Flat versus reducing ─────────────────────────────────────────────────────

/**
 * The reducing rate that a FLAT rate actually is.
 *
 * A flat rate charges interest on the whole original amount for the whole tenure, even though the
 * borrower has repaid most of it by the end. The Reserve Bank requires the effective reducing rate
 * to be disclosed for exactly this reason — and it is close to double the flat number, which almost
 * nobody expects.
 *
 * There is no formula for it. It is solved for: find the reducing rate whose instalment equals the
 * one the flat calculation produced.
 */
export function effectiveMonthlyRate(principalPaise: bigint, emiPaise: bigint, months: number): number {
  const P = Number(principalPaise);
  const target = Number(emiPaise);
  if (P <= 0 || months <= 0 || target <= 0) return 0;
  let lo = 0, hi = 1;
  for (let i = 0; i < 100; i++) {
    const mid = (lo + hi) / 2;
    const factor = Math.pow(1 + mid, months);
    const pmt = mid === 0 ? P / months : (P * mid * factor) / (factor - 1);
    if (pmt > target) hi = mid;
    else lo = mid;
  }
  return (lo + hi) / 2;
}

/** The instalment a flat rate produces, and the reducing rate it really is. */
export function flatRate(principalPaise: bigint, flatPct: number, months: number) {
  const totalInterest = BigInt(Math.round(Number(principalPaise) * (flatPct / 100) * (months / 12)));
  const emi = roundToRupee((principalPaise + totalInterest) / BigInt(months || 1));
  const eff = effectiveMonthlyRate(principalPaise, emi, months);
  return {
    emiPaise: emi,
    totalInterestPaise: totalInterest,
    effectiveReducingPct: Math.round(eff * 12 * 10_000) / 100,
  };
}

// ── The gold LTV cap, which is not one number ────────────────────────────────

/**
 * The cap depends on the SIZE of the advance, not only on the security.
 *
 * The Directions effective 1 April 2026 replaced the flat 75% with three bands: up to ₹2.5 lakh the
 * cap is 85%, from there to ₹5 lakh it is 80%, and above ₹5 lakh it is 75%. Small-ticket borrowers
 * get more against the same ornaments; large ones get less.
 *
 * A calculator defaulting to a flat 75% therefore understates what may be advanced on most gold
 * loans written in India, which are small.
 *
 * Source: RBI (Lending Against Gold and Silver Collateral) Directions, 2025.
 */
export const LTV_BANDS = [
  { upToPaise: 25_000_000n, capPct: 85, label: "up to ₹2.5 lakh" },
  { upToPaise: 50_000_000n, capPct: 80, label: "₹2.5 lakh to ₹5 lakh" },
  { upToPaise: null, capPct: 75, label: "above ₹5 lakh" },
] as const;

/** The cap that applies to an advance of this size. */
export function capForAdvance(advancePaise: bigint): { capPct: number; label: string } {
  for (const b of LTV_BANDS) {
    if (b.upToPaise === null || advancePaise <= b.upToPaise) return { capPct: b.capPct, label: b.label };
  }
  return { capPct: 75, label: "above ₹5 lakh" };
}

/**
 * The largest advance the bands permit against a given eligible value.
 *
 * Circular on its face — the cap depends on the advance, and the advance depends on the cap — so it
 * is solved band by band, highest first, keeping the largest that is internally consistent.
 */
export function maxAdvanceBanded(eligiblePaise: bigint): { advancePaise: bigint; capPct: number; label: string } {
  const candidates: { advancePaise: bigint; capPct: number; label: string }[] = [];
  for (const b of LTV_BANDS) {
    const atCap = maxLendablePaise(eligiblePaise, b.capPct);
    const advance = b.upToPaise === null ? atCap : atCap < b.upToPaise ? atCap : b.upToPaise;
    const lower = LTV_BANDS.indexOf(b as never) === 0 ? 0n : LTV_BANDS[LTV_BANDS.indexOf(b as never) - 1].upToPaise!;
    // Consistent only if an advance of this size really falls in this band.
    if (advance > lower && (b.upToPaise === null || advance <= b.upToPaise)) {
      candidates.push({ advancePaise: advance, capPct: b.capPct, label: b.label });
    }
  }
  if (candidates.length === 0) return { advancePaise: 0n, capPct: 85, label: LTV_BANDS[0].label };
  return candidates.reduce((a, b) => (b.advancePaise > a.advancePaise ? b : a));
}
