import Link from "next/link";
import { Section, SectionHead, Spec, ButtonLink } from "@/components/ui";
import { Reveal } from "@/components/reveal";
import { Shot } from "@/components/shot";
import { absolute, COMPANY, SITE } from "@/lib/site";
import type { ProductSection, ProductSpec } from "@/lib/products/types";

/**
 * The skeleton every product page renders through — heading order and CTA, nothing else.
 *
 * What is deliberately NOT here: any sentence. All prose comes from the spec, because four pages
 * that differ only by a swapped noun are the doorway pattern and would be treated as
 * near-duplicates. See `src/lib/products/types.ts` for the test each string had to pass.
 */
function SpecList({ section }: { section: ProductSection }) {
  return (
    <>
      <SectionHead title={section.head} lead={section.lead} />
      <dl className="mt-s4 border-b border-line">
        {section.points.map(([term, body]) => (
          <Reveal key={term}>
            <Spec term={term}>{body}</Spec>
          </Reveal>
        ))}
      </dl>
    </>
  );
}

export function ProductPage({ spec }: { spec: ProductSpec }) {
  const url = absolute(`/${spec.slug}/`);

  /**
   * The SAME `SoftwareApplication` as the root layout's, described more specifically here.
   *
   * The `@id` is the point. Without it this page emitted a second SoftwareApplication node with a
   * different name, so a consumer reading the page saw two applications where there is one — the
   * "duplicate or conflicting schema generated by multiple components" that structured-data
   * guidance warns about, and self-inflicted. Both nodes now carry the same `@id`, which is the
   * standard way to say *this is that entity, here is more about it*: the layout supplies the
   * product, this supplies what it does for this asset class.
   *
   * No `aggregateRating`, no `review`, no `offers`. All three would have to be invented, and
   * inventing them is what makes structured data a liability rather than an asset — a machine
   * reading this will not notice that a rating is fictional. It also means this will not produce a
   * software rich result, which requires exactly those fields. That is the correct trade.
   */
  const app = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": `${SITE.url}/#software`,
    name: SITE.name,
    applicationCategory: "BusinessApplication",
    applicationSubCategory: spec.title,
    operatingSystem: "Web",
    description: spec.description,
    url,
    publisher: { "@type": "Organization", name: COMPANY.legalName },
    audience: { "@type": "Audience", audienceType: "Non-Banking Financial Companies in India" },
  };

  const crumbs = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: absolute("/") },
      { "@type": "ListItem", position: 2, name: "Platform", item: absolute("/platform/") },
      { "@type": "ListItem", position: 3, name: spec.eyebrow, item: url },
    ],
  };

  /**
   * `FAQPage`, on a page whose FAQ block is genuinely visible.
   *
   * It earns no rich result and has not since 7 May 2026, when Google withdrew the feature
   * entirely — the narrow government-and-health eligibility that survived August 2023 went with
   * it, and the documentation was removed on 15 June 2026. It is emitted anyway because the type
   * is still valid, Google still parses it to understand the page, and the questions below are
   * real ones that a person asked. What is NOT done is the thing the deprecation should stop:
   * writing questions that exist only to carry markup.
   */
  const faq = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: spec.faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(app) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(crumbs) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} />

      <Section className="pt-s7">
        <Reveal>
          <nav className="text-[13px] text-muted">
            <Link href="/platform/" className="hover:text-ink">
              The platform
            </Link>
            <span aria-hidden="true"> · </span>
            <span>{spec.eyebrow}</span>
          </nav>
          <h1 className="mt-s2 max-w-4xl text-[34px] font-extrabold leading-[1.1] tracking-display-tight text-ink sm:text-[46px]">
            {spec.h1}
          </h1>
          {spec.intro.map((p) => (
            <p key={p.slice(0, 24)} className="mt-s4 max-w-prose text-[18px] leading-prose text-slate-mid">
              {p}
            </p>
          ))}
        </Reveal>
        <Shot {...spec.shots.afterIntro} />
      </Section>

      <Section tone="sand">
        <SpecList section={spec.lifecycle} />
      </Section>

      {/* The section that carries the page: what is true of this asset class and no other. */}
      <Section>
        <SpecList section={spec.specific} />
        <Shot {...spec.shots.afterSpecific} />
      </Section>

      <Section tone="sand">
        <SpecList section={spec.compliance} />
        <p className="mt-s4 max-w-prose text-[15px] leading-relaxed text-slate-mid">
          Every position above is implemented against a named direction. The{" "}
          <Link href="/compliance/" className="underline decoration-line-strong underline-offset-4 hover:text-ink">
            compliance page
          </Link>{" "}
          sets out each one with the instrument it comes from and its date.
        </p>
      </Section>

      <Section>
        <SpecList section={spec.documents} />
      </Section>

      <Section tone="sand">
        <SpecList section={spec.reports} />
        <p className="mt-s4 max-w-prose text-[15px] leading-relaxed text-slate-mid">
          Each names the one question it answers and the date it is as at. The{" "}
          <Link href="/reports/" className="underline decoration-line-strong underline-offset-4 hover:text-ink">
            full reporting catalogue
          </Link>{" "}
          lists what is available across the book.
        </p>
      </Section>

      <Section>
        <SectionHead eyebrow="Questions" title="What lenders ask about this book" />
        <dl className="mt-s4 border-b border-line">
          {spec.faqs.map((f) => (
            <Reveal key={f.q}>
              <Spec term={f.q}>{f.a}</Spec>
            </Reveal>
          ))}
        </dl>
      </Section>

      <Section tone="sand">
        <SectionHead eyebrow="Related" title="Read further" />
        <ul className="mt-s4 space-y-s3">
          {spec.related.map((r) => (
            <Reveal key={r.href}>
              <li className="border-t border-line pt-s3">
                <Link
                  href={r.href}
                  className="font-display text-[16px] font-bold tracking-display text-ink underline decoration-line-strong underline-offset-4 hover:text-cta"
                >
                  {r.label}
                </Link>
                <p className="mt-1 text-[15px] leading-relaxed text-slate-mid">{r.note}</p>
              </li>
            </Reveal>
          ))}
        </ul>
      </Section>

      <Section>
        <Reveal>
          <h2 className="max-w-3xl text-[30px] font-bold leading-[1.15] tracking-display text-ink sm:text-[36px]">
            See it against your own book.
          </h2>
          <p className="mt-s3 max-w-prose text-[16px] leading-prose text-slate-mid">
            A demonstration runs on your product mix rather than a script — bring the case you think
            is hardest.
          </p>
          <div className="mt-s4 flex flex-wrap gap-s3">
            <ButtonLink href="/contact/">Request a demo</ButtonLink>
            <ButtonLink href={SITE.appUrl} variant="secondary" external>
              Login
            </ButtonLink>
          </div>
        </Reveal>
      </Section>
    </>
  );
}
