import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";
import { Section, SectionHead, Card, Spec, ButtonLink } from "@/components/ui";
import { Reveal } from "@/components/reveal";
import { Shot, PhoneShot } from "@/components/shot";
import { PRODUCTS } from "@/lib/products";

export const metadata: Metadata = pageMetadata({
  /*
   * "NBFC software" is what a buyer types, and this page did not use the phrase — it opened on
   * "Loan origination and management system", which is what the category is called by people who
   * already work in it. The URL stays: a rename would move whatever standing this path has for the
   * sake of a keyword in a slug, which is not worth much any more.
   */
  title: "NBFC software: origination, loan management and the accounting under both",
  description:
    "NBFC software for the whole lifecycle: lead to disbursement, servicing, collections, day-end IRAC classification and provisioning, and the accounting under it.",
  path: "/platform/",
});

/**
 * The questions a lender asks before a shortlist — and this page had none, though it is the page
 * they get asked on. Also emitted as `FAQPage`, which is the shape an answer engine lifts.
 *
 * Plain strings, because a JSX fragment cannot be serialised into structured data.
 */
const FAQS = [
  {
    q: "What is NBFC software, and how is it different from a loan management system?",
    a: "A loan management system services a loan that already exists — schedules, receipts, interest, classification. NBFC software is the whole lifecycle around it: origination before the loan exists, the accounting under it, and the returns that come out of it. Buying only the servicing half leaves the origination in spreadsheets and the ledger in a second system, which is where most reconciliation work comes from.",
  },
  {
    q: "Which loan products does it run?",
    a: "Gold, property, personal, business and vehicle loans, and overdraft and cash credit limits. Each one binds by its behaviour rather than its name, so a scheme is configured rather than coded — a gold loan is priced by an approved daily rate and a purity-adjusted weight, a cash credit accrues daily on the drawn balance against a drawing power, and both post to their own ledgers.",
  },
  {
    q: "Does it do the accounting, or does that stay in Tally?",
    a: "It does the accounting. Loan events generate double-entry vouchers into a chart of accounts a Tally-trained accountant recognises, with GST on fees, and TDS receivable tracked quarter-wise against the certificate and 26AS status. A trial balance that foots is the point: a lending system whose figures have to be re-keyed into a ledger has moved the reconciliation rather than removed it.",
  },
  {
    q: "How are NPA and provisioning handled?",
    a: "Classification is computed in the day-end batch, never on request, so a report at 11am and one at 6pm describe the same day. Provisioning follows the NBFC rates rather than the bank ones — 10% on a sub-standard asset, and a doubtful exposure split with the secured portion at 20, 30 or 50% by age and the rest at 100% — and the standard-asset rate follows the tenant's layer.",
  },
  {
    q: "Can it be configured, or does every lender get the same rules?",
    a: "The commercial choices are configurable: rate bands, charge amounts, penal grace, approval slabs, repayment shapes. The regulatory positions are not. An SMA boundary or a ninety-day trigger a tenant could move is a setting that produces a wrong return.",
  },
  {
    q: "What does it take to go live?",
    a: "A chart of accounts, opening balances as at a migration date, the schemes you lend under, and your branches and users. The book is entered at a stated date and everything after it is generated by the system rather than typed, which is what makes the audit trail worth having.",
  },
];

const LOS = [
  ["Leads and applications", "Capture, assignment and a stage-by-stage workflow to sanction, with turnaround visible per stage."],
  ["Parties", "Individual and non-individual borrowers, co-applicants and guarantors, with the KYC each constitution actually requires."],
  ["Collateral", "Property and gold today, each valued and tracked under its own rules — gold by purity and net weight, property by valuation and charge."],
  ["Credit", "Bureau pulls recorded against the application with the report attached, scoring bands, and approval slabs that route by amount."],
  ["Sanction and disbursement", "Sanction snapshots the scheme's terms, so a later change to the scheme cannot alter a loan already sanctioned. Disbursement is maker-checker."],
];

/**
 * The loan lifecycle as a reader would narrate it — numbered because it genuinely is a sequence,
 * which is the only reason to number anything.
 */
const LIFECYCLE: [string, string][] = [
  ["Loan origination", "A lead becomes an application, with the borrower, co-applicants and guarantors held as party records rather than as fields on a form — so a second loan starts from what is already known."],
  ["Credit and underwriting", "Bureau pulls recorded against the file with the report attached, income and obligations assessed into a ratio whose workings are stored, and deviations that carry the approval level they require."],
  ["Approval", "An approval matrix routes by sanctioned amount through its slabs. Master activation and disbursement are maker-checker: the person who prepares is never the person who releases."],
  ["Documentation", "The sanction and disbursement pack generated from the loan\u2019s own terms — application, agreement for the asset class, Key Facts Statement, promissory note, mandate — on your letterhead, with the borrower declaration in fourteen languages."],
  ["Disbursement", "Released against the sanctioned terms, with the funding instrument recorded and the accounting entry posted as it happens rather than at month end."],
  ["Loan servicing", "Schedules, receipts, part payment and foreclosure. Seven repayment shapes, because a gold loan and a twenty-year property loan do not repay alike."],
  ["Interest and charges", "Interest accrued nightly on the balance outstanding that day. Charges levied under their own rules — penal amounts as charges rather than interest, never compounded and never added to principal."],
  ["Collections", "Allocation, follow-up and field collection on a phone that works without a signal, with a receipt that cannot post twice if the network retries."],
  ["Accounting", "Double-entry vouchers generated from the loan events themselves, into a chart of accounts a Tally-trained accountant recognises. GST on fees, TDS against certificates, statements that foot."],
  ["Compliance and reporting", "Day-end IRAC classification, SMA buckets, provisioning and income reversal on NPA — then the returns and the operational MIS that follow from them, each naming the date it is as at."],
  ["Audit trail", "Every mutation writes who, when, and the before and after. Sanction, disbursement and rejection are immutable events; a correction is a reversing entry, never an edit. This is the stage that makes the other ten defensible."],
];

const LMS = [
  ["Servicing", "Schedules, repayments, receipts, part payment and foreclosure, with the statutory bar on pre-payment charges applied by the system rather than by the scheme."],
  ["Collections", "Allocation, follow-up, and collection efficiency measured the way a lender's diligence pack asks for it."],
  ["Asset quality", "DPD, SMA buckets, IRAC classification and provisioning, computed at day-end in a scheduled job."],
  ["Gold", "Purity, LTV against the day's rate, renewal pipeline and auction tracking."],
  ["Borrowings", "The liability side: facilities, drawdowns, drawing power from the day-end statement, and the security pool pledged against each."],
];

export default function PlatformPage() {
  const faqLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQS.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />
      <Section className="pt-s7">
        <Reveal>
          <p className="text-[13px] font-semibold uppercase tracking-wide text-cta">The platform</p>
          <h1 className="mt-s2 max-w-4xl text-[34px] font-extrabold leading-[1.1] tracking-display-tight text-ink sm:text-[46px]">
            NBFC software, from the lead to the closure letter.
          </h1>
          <p className="mt-s4 max-w-prose text-[18px] leading-prose text-slate-mid">
            Most lenders run an origination system, a servicing system and an accounting package,
            and spend the last week of every month reconciling them. Here the loan event posts to
            the books as it happens, so there is one set of facts.
          </p>
        </Reveal>
        {/*
          * Nine screens of page, and no way to see what is on it.
          *
          * This is the page a prospect is sent to, and it runs to 9,378px. Somebody who wants to
          * know what it does about accounting was scrolling past six sections to find out, or
          * giving up. Every long product page a buyer compares this against — Stripe's, Zoho's —
          * carries a jump list; this one had not even given its sections an id, so no part of it
          * could be linked to in an email either.
          *
          * Inline rather than sticky: the header already sticks, and a second fixed strip plus the
          * WhatsApp button is more chrome than a reading page can carry.
          */}
        <Reveal>
          <nav aria-label="On this page" className="mt-s5 flex flex-wrap gap-x-s4 gap-y-s2 border-y border-line py-s3 text-[15px]">
            {[
              ["#lifecycle", "The lifecycle"],
              ["#origination", "Origination"],
              ["#servicing", "Servicing"],
              ["#field", "The field app"],
              ["#accounting", "Accounting"],
              ["#books", "Books and returns"],
              ["#pilot", "What a pilot looks like"],
            ].map(([href, label]) => (
              // `py-1` takes the link from 23px to 31px. WCAG 2.5.8 asks for 24 and these were one
              // pixel under. Inline links inside a sentence are exempt from that rule; these are
              // not inline — they are a standalone jump list a thumb has to hit.
              <a key={href} href={href} className="py-1 text-slate-mid underline-offset-4 transition-colors hover:text-cta hover:underline">
                {label}
              </a>
            ))}
          </nav>
        </Reveal>

        {/*
          * The product, above the argument for it.
          *
          * A buyer evaluating a lending platform wants to see a loan file before they read a list of
          * modules. This is a real one, generated from the running software — see `Shot`.
          */}
        <Shot
          name="application-stages"
          priority
          alt="A loan application in Lenviq showing the workflow header with the current stage, what is blocking the next one, the approval status and the sanctioned amount"
          caption="A loan file, with the next step and what is blocking it above everything else."
        />
      </Section>

      {/*
        * The lifecycle end to end, before the module lists.
        *
        * The two lists below are good at saying what the system HAS. Neither says what actually
        * happens to a loan, in order, and that is the question somebody evaluating a lending
        * platform is really asking — five of these stages had no mention anywhere on the page
        * (documentation, interest and charges, compliance, reporting, the audit trail) even though
        * all five are the product. Named stages also give the page the vocabulary a reader is
        * searching with, without a keyword being written twice.
        */}
      <Section id="lifecycle" tone="sand">
        <SectionHead
          eyebrow="The lifecycle"
          title="What happens to a loan, in order"
          lead="Eleven stages, one system. The point is not that each exists — it is that a loan carries its record forward through all of them, so the answer at the end can be traced to the event at the beginning."
        />
        <ol className="mt-s5 grid gap-s3 md:grid-cols-2">
          {LIFECYCLE.map(([stage, body], i) => (
            <Reveal key={stage} stage={((i % 3) + 1) as 1 | 2 | 3}>
              <li className="h-full rounded-card border border-line bg-card p-s4">
                <p className="font-display text-[13px] font-bold uppercase tracking-wide text-cta">
                  {String(i + 1).padStart(2, "0")}
                </p>
                <h3 className="mt-1 font-display text-[17px] font-bold tracking-display text-ink">{stage}</h3>
                <p className="mt-s2 text-[15px] leading-relaxed text-slate-mid">{body}</p>
              </li>
            </Reveal>
          ))}
        </ol>
      </Section>

      <Section id="origination">
        <SectionHead eyebrow="Origination" title="Lead to disbursement" />
        <dl className="mt-s4 border-b border-line">
          {LOS.map(([t, b]) => <Reveal key={t}><Spec term={t}>{b}</Spec></Reveal>)}
        </dl>
        <Shot
          name="party-kyc"
          alt="A borrower record in Lenviq showing the profile and the KYC and customer-risk panel, with the money-laundering risk category, sanctions screening and the re-KYC schedule"
          caption="Everything about a borrower lives on the customer, not on the loan file — so a second loan starts from what is already known."
        />
      </Section>

      <Section id="servicing">
        <SectionHead eyebrow="Loan management" title="Disbursement to closure" />
        <dl className="mt-s4 border-b border-line">
          {LMS.map(([t, b]) => <Reveal key={t}><Spec term={t}>{b}</Spec></Reveal>)}
        </dl>
        <Shot
          name="loan-account"
          alt="A live loan account in Lenviq showing its overdue status and days past due, the sanctioned terms, the outstanding principal and penal balance, and tabs for the schedule, transactions, statement and charges"
          caption="The position at the top of the account, and every figure behind it one tab away."
        />
      </Section>

      {/*
        * The field app, which is the half of the product a competitor's screenshot never shows.
        */}
      <Section id="field" tone="sand">
        <SectionHead
          eyebrow="In the field"
          title="The round, on the phone that is already in their pocket"
          lead="Collections, lead capture and field investigation, built for a hand and a street — and for no signal, which on a round is normal rather than exceptional."
        />
        <div className="mt-s4 grid gap-s5 sm:grid-cols-2">
          <PhoneShot
            name="field-account-summary"
            alt="The Lenviq field app showing a borrower's account summary with its SMA classification, the overdue position broken into penal, bounce, interest and principal, and the total payable now"
            caption="What the borrower will ask, before they ask it."
          />
          <PhoneShot
            name="field-accounts"
            alt="The Lenviq field app showing a collection agent's loan accounts filtered by overdue, due today, regular and NPA"
            caption="The agent's whole book, not only today's doors."
          />
        </div>
        <p className="mt-s4 max-w-prose text-[16px] leading-prose text-slate-mid">
          Every screen here works with no network. A collection is held on the phone with its
          photograph and its location and sent when a tower appears — and the receipt is idempotent,
          so a retry cannot post a second payment against a borrower&rsquo;s loan.
        </p>
        <p className="mt-s4">
          <ButtonLink href="/help/collect-a-payment-in-the-field/" variant="secondary">
            How a collection is recorded
          </ButtonLink>
        </p>
      </Section>

      <Section id="accounting" tone="sand">
        <SectionHead
          eyebrow="Accounting"
          title="Double entry, not a summary"
          lead="A chart of accounts a Tally-trained accountant recognises, postings generated from the loan events themselves, and statements that foot."
        />
        <div className="mt-s5 grid gap-s3 md:grid-cols-3">
          <Reveal stage={1}><Card title="Chart of accounts">Groups and ledgers in the shape an Indian accountant expects, with branch-wise cash and bank accounts.</Card></Reveal>
          <Reveal stage={2}><Card title="GST and TDS">Output GST on fees with the CGST/SGST/IGST split, TDS receivable tracked against certificates.</Card></Reveal>
          <Reveal stage={3}><Card title="Statements">Trial balance, profit and loss, and a balance sheet that refuses to render if it does not foot — rather than rendering and being wrong.</Card></Reveal>
        </div>
      </Section>

      {/*
        * The four asset classes, each with its own page.
        *
        * Placed after the platform is described rather than before it: somebody arriving on
        * /platform/ is asking what the system does, and the product-specific pages answer the
        * narrower question they ask next. Section 7 of the brief — the platform page links out to
        * all four — and each anchor says what the page is rather than naming the loan.
        */}
      <Section id="books">
        <SectionHead
          eyebrow="By loan product"
          title="Four books, one system"
          lead="Asset-class behaviour is configuration, not four code paths — but what each book actually demands of the software is different enough to be worth setting out on its own."
        />
        <div className="mt-s5 grid gap-s3 md:grid-cols-2">
          {PRODUCTS.map((p, i) => (
            <Reveal key={p.slug} stage={((i % 3) + 1) as 1 | 2 | 3}>
              <Card href={`/${p.slug}/`} title={p.title.replace(/ for NBFCs.*$/, "").replace(/ —.*$/, "")}>
                {p.description}
              </Card>
            </Reveal>
          ))}
        </div>
      </Section>

      <Section id="pilot">
        <SectionHead
          eyebrow="Implementation"
          title="What a pilot actually looks like"
          lead="Reducing perceived risk moves more decisions in this market than another feature does, so here is the shape of it rather than a promise about it."
        />
        <div className="mt-s5 grid gap-s3 md:grid-cols-3">
          <Reveal stage={1}><Card title="1 · Pilot">One branch, one or two products, a subset of the live book. Your schemes, your rates, your document templates on your letterhead.</Card></Reveal>
          <Reveal stage={2}><Card title="2 · Migration">Borrowers, loans, schedules and outstanding balances come across with their history. Opening balances are entered as an opening trial balance, so the books start reconciled.</Card></Reveal>
          <Reveal stage={3}><Card title="3 · Run">Parallel running for a cycle or two is normal and we plan for it. The point at which you stop is your call, not a project milestone.</Card></Reveal>
        </div>
        <Reveal className="mt-s5">
          <p className="max-w-prose text-[15px] leading-prose text-muted">
            Timelines depend on the state of the data you are migrating from, which is the honest
            answer — we would rather scope that with you than publish a number that turns out to be
            somebody else&rsquo;s.
          </p>
        </Reveal>
      </Section>

      <Section tone="sand">
        <Reveal className="flex flex-wrap items-center justify-between gap-s3 rounded-card border border-sand-border bg-card p-s6">
          <p className="max-w-prose text-[17px] leading-prose text-slate-mid">
            The fastest way to judge fit is to see it against your own product mix.
          </p>
          <ButtonLink href="/contact/">Request a demo</ButtonLink>
        </Reveal>
      </Section>
      {/*
        * The questions a lender asks before a shortlist. The blog posts and the compliance page
        * carry an FAQ and the product page did not, though it is the page those questions land on.
        * Also emits FAQPage, which is the shape an answer engine lifts.
        */}
      <Section id="questions">
        <SectionHead eyebrow="Questions" title="What lenders ask before a shortlist" />
        <dl className="mt-s5 max-w-prose">
          {FAQS.map((f) => (
            <Reveal key={f.q}>
              <div className="border-b border-line py-s4">
                <dt className="font-display text-[18px] font-bold tracking-display text-ink">{f.q}</dt>
                <dd className="mt-s2 text-[16px] leading-prose text-slate-mid">{f.a}</dd>
              </div>
            </Reveal>
          ))}
        </dl>
      </Section>

    </>
  );
}
