/**
 * Stamp the build with the commit it came from.
 *
 * Without this there is no way to ask a running site which version it is. The site does not look
 * wrong when it is stale — it looks like an older correct site — so a deploy that was skipped is
 * invisible until somebody happens to check a sentence they remember changing. That happened: three
 * commits sat undeployed while the site served an earlier one and nothing anywhere said so.
 *
 * Two outputs, because they answer the question in different places:
 *   public/build-info.json      — for `curl`, and for a cron that compares against main
 *   src/lib/build-info.generated.ts — for a <meta> tag, so any page in a browser can be identified
 *
 * Runs from `predev` and `prebuild`, and degrades rather than failing: a deploy from a tarball with
 * no git history stamps "unknown" and still builds. A stamp that breaks the build would be worse
 * than no stamp.
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const git = (cmd, fallback) => {
  try {
    return execSync(`git ${cmd}`, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return fallback;
  }
};

const commit = git("rev-parse HEAD", "unknown");
const subject = git("log -1 --format=%s", "");
const committedAt = git("log -1 --format=%cI", "");
// A build from a dirty tree is not the commit it claims to be, and saying so is the whole point.
const dirty = git("status --porcelain", "") !== "";
const builtAt = new Date().toISOString();

const info = {
  commit,
  shortCommit: commit.slice(0, 7),
  subject,
  committedAt,
  builtAt,
  dirty,
};

mkdirSync(join(ROOT, "public"), { recursive: true });
writeFileSync(join(ROOT, "public/build-info.json"), JSON.stringify(info, null, 2) + "\n");

mkdirSync(join(ROOT, "src/lib"), { recursive: true });
writeFileSync(
  join(ROOT, "src/lib/build-info.generated.ts"),
  "/* GENERATED by scripts/build-stamp.mjs. Do not edit, and do not commit. */\n" +
    `export const BUILD = ${JSON.stringify(info, null, 2)} as const;\n`,
);

console.log(`[stamp] ${info.shortCommit}${dirty ? " (dirty)" : ""} — ${subject.slice(0, 60)}`);
