/**
 * Copy the generated brand assets into each application's `public/`.
 *
 * `brand/` is the single source. Next.js can only serve what sits in `public/`, so the choice is
 * either a copy step or a second set of files maintained by hand — and a second set is how a
 * favicon ends up one revision behind a logo with nobody noticing, which is the same shape as
 * every other "one truth, two copies" defect in this repo.
 *
 * Runs from `prebuild`, so a build cannot ship stale assets.
 *
 * In this repository there is one consumer — the site itself, at the root. The product's copy of
 * this script syncs two; the difference is the APPS list below and nothing else, so a fix to the
 * copying logic can be moved across unchanged.
 */
import { cpSync, mkdirSync, existsSync, copyFileSync, writeFileSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const SRC = join(ROOT, "brand/public");
if (!existsSync(SRC)) {
  console.error("[brand] brand/public is missing — run `node scripts/build-brand.mjs` first.");
  process.exit(1);
}

/** One consumer: this repository is the site. */
const APPS = [{ root: ROOT, label: "site" }];

const BANNER = "/* GENERATED by scripts/sync-brand.mjs from brand/. Do not edit — edit the source. */\n";

for (const app of APPS) {
  if (!existsSync(app.root)) continue;

  const pub = join(app.root, "public");
  mkdirSync(pub, { recursive: true });
  cpSync(SRC, pub, { recursive: true });
  cpSync(join(ROOT, "brand/logo"), join(pub, "brand"), { recursive: true });

  // The woff2 files are served from /fonts, which is the path the generated @font-face rules use.
  mkdirSync(join(pub, "fonts"), { recursive: true });
  for (const f of readdirSync(join(ROOT, "brand/fonts")).filter((f) => f.endsWith(".woff2"))) {
    copyFileSync(join(ROOT, "brand/fonts", f), join(pub, "fonts", f));
  }
  // The OFL requires the licence to travel with the files.
  for (const f of readdirSync(join(ROOT, "brand/fonts")).filter((f) => f.startsWith("LICENSE"))) {
    copyFileSync(join(ROOT, "brand/fonts", f), join(pub, "fonts", f));
  }

  // Stylesheets go beside the app's own CSS so they import with a relative path.
  const styles = join(app.root, "src/styles");
  mkdirSync(styles, { recursive: true });
  for (const [src, name] of [
    [join(ROOT, "brand/tokens.css"), "tokens.generated.css"],
    [join(ROOT, "brand/fonts/fonts.css"), "fonts.generated.css"],
  ]) {
    writeFileSync(join(styles, name), BANNER + readFileSync(src, "utf8"));
  }

  console.log(`[brand] → ${app.label}`);
}
